from decimal import Decimal
from django.conf import settings
from django.db import migrations,models
import django.db.models.deletion
class Migration(migrations.Migration):
    dependencies=[('store','0002_remove_product_additional_images_and_more'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
      migrations.CreateModel(name='Cart',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('updated_at',models.DateTimeField(auto_now=True)),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='cart',to=settings.AUTH_USER_MODEL))]),
      migrations.CreateModel(name='Order',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=160)),('email',models.EmailField(max_length=254)),('phone',models.CharField(max_length=30)),('address',models.TextField()),('city',models.CharField(max_length=100)),('postal_code',models.CharField(max_length=20)),('subtotal',models.DecimalField(decimal_places=2,max_digits=10)),('delivery_charge',models.DecimalField(decimal_places=2,default=Decimal('80.00'),max_digits=10)),('total',models.DecimalField(decimal_places=2,max_digits=10)),('status',models.CharField(choices=[('confirmed','Confirmed'),('shipped','Shipped'),('delivered','Delivered'),('cancelled','Cancelled')],default='confirmed',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('user',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='orders',to=settings.AUTH_USER_MODEL))],options={'ordering':['-created_at']}),
      migrations.CreateModel(name='CartItem',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('size',models.CharField(blank=True,max_length=60)),('color',models.CharField(blank=True,max_length=60)),('quantity',models.PositiveIntegerField(default=1)),('cart',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='items',to='store.cart')),('product',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='store.product'))]),
      migrations.CreateModel(name='OrderItem',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('product_name',models.CharField(max_length=160)),('size',models.CharField(blank=True,max_length=60)),('color',models.CharField(blank=True,max_length=60)),('unit_price',models.DecimalField(decimal_places=2,max_digits=10)),('quantity',models.PositiveIntegerField()),('line_total',models.DecimalField(decimal_places=2,max_digits=10)),('order',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='items',to='store.order')),('product',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='store.product'))]),
      migrations.AddConstraint(model_name='cartitem',constraint=models.UniqueConstraint(fields=('cart','product','size','color'),name='unique_cart_product_option')),
    ]
