from django.db import migrations,models

def seed_banners(apps,schema_editor):
    Banner=apps.get_model('store','Banner')
    Banner.objects.get_or_create(title='Prints made to be remembered.',defaults={'placement':'hero','eyebrow':'The Rose Garden Edit','description':'Expressive florals, considered details, and an effortless silhouette for celebrations and slow afternoons.','desktop_image':'banners/desktop/nazriy-look-1.jpeg','image_alt':'NazRiy burgundy floral outfit','primary_button_label':'Shop now','primary_button_link':'/products','secondary_button_label':'Explore the edit','secondary_button_link':'#featured','theme':'burgundy','object_position':'center 42%','sort_order':1,'active':True})
    Banner.objects.get_or_create(title='A closer look at thoughtful design.',defaults={'placement':'hero','eyebrow':'Crafted in detail','description':'Rich colour and delicate finishing touches turn an everyday piece into something distinctly yours.','desktop_image':'banners/desktop/nazriy-detail.jpeg','image_alt':'Close-up of NazRiy floral details','primary_button_label':'Shop now','primary_button_link':'/products','secondary_button_label':'Explore the edit','secondary_button_link':'#featured','theme':'forest','object_position':'center 48%','sort_order':2,'active':True})

class Migration(migrations.Migration):
    dependencies=[('store','0003_sprint3_commerce')]
    operations=[migrations.CreateModel(name='Banner',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('placement',models.CharField(choices=[('hero','Homepage hero'),('promotion','Promotional banner'),('category','Category banner')],default='hero',max_length=20)),('eyebrow',models.CharField(blank=True,max_length=100)),('title',models.CharField(max_length=180)),('description',models.TextField(blank=True)),('desktop_image',models.FileField(upload_to='banners/desktop/')),('mobile_image',models.FileField(blank=True,upload_to='banners/mobile/')),('image_alt',models.CharField(max_length=180)),('primary_button_label',models.CharField(default='Shop now',max_length=60)),('primary_button_link',models.CharField(default='/products',max_length=240)),('secondary_button_label',models.CharField(blank=True,max_length=60)),('secondary_button_link',models.CharField(blank=True,max_length=240)),('theme',models.CharField(choices=[('forest','Forest'),('burgundy','Burgundy'),('sage','Sage'),('neutral','Neutral')],default='forest',max_length=20)),('object_position',models.CharField(default='center center',help_text='CSS object-position, for example: center 42%',max_length=40)),('sort_order',models.PositiveSmallIntegerField(default=0)),('active',models.BooleanField(default=True)),('starts_at',models.DateTimeField(blank=True,null=True)),('ends_at',models.DateTimeField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True))],options={'ordering':['sort_order','id']}),migrations.RunPython(seed_banners,migrations.RunPython.noop)]
