# Generated by Django 6.0.6 on 2026-08-14 12:44

import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.db import migrations, models


def configure_existing_campaigns(apps, schema_editor):
    Campaign = apps.get_model('store', 'DiscountCampaign')
    seen_codes = set()
    for campaign in Campaign.objects.order_by('pk'):
        code = (campaign.discount_code or '').strip().upper()
        if code and code in seen_codes:
            code = f'{code[:32]}-{campaign.pk}'
        campaign.discount_code = code
        if code:
            seen_codes.add(code)
        if campaign.name == 'Demo — Welcome offer':
            campaign.discount_type = 'percentage'
            campaign.discount_value = Decimal('10.00')
            campaign.minimum_order_amount = Decimal('500.00')
            campaign.maximum_discount_amount = Decimal('500.00')
        elif campaign.name == 'Demo — Festive collection':
            campaign.discount_type = 'percentage'
            campaign.discount_value = Decimal('15.00')
            campaign.minimum_order_amount = Decimal('1000.00')
            campaign.maximum_discount_amount = Decimal('750.00')
        elif campaign.name == 'Demo — Free delivery weekend':
            campaign.discount_type = 'free_delivery'
            campaign.discount_value = Decimal('0.00')
            campaign.minimum_order_amount = Decimal('500.00')
            campaign.maximum_discount_amount = None
        campaign.save(update_fields=[
            'discount_code', 'discount_type', 'discount_value',
            'minimum_order_amount', 'maximum_discount_amount',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_bkash_gateway_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcampaign',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage off'), ('fixed', 'Fixed amount off'), ('free_delivery', 'Free delivery')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='discountcampaign',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Percentage or fixed BDT amount. Ignored for free delivery.', max_digits=10),
        ),
        migrations.AddField(
            model_name='discountcampaign',
            name='maximum_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional cap for percentage discounts.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='discountcampaign',
            name='minimum_order_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='discountcampaign',
            name='per_customer_limit',
            field=models.PositiveSmallIntegerField(default=1, help_text='Maximum non-cancelled orders per customer.'),
        ),
        migrations.AddField(
            model_name='discountcampaign',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum successful checkouts across all customers. Leave blank for unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.discountcampaign'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.RunPython(configure_existing_campaigns, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='discountcampaign',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('discount_code'), condition=models.Q(('discount_code', ''), _negated=True), name='unique_discount_campaign_code_ci'),
        ),
    ]
