import { useState,type FormEvent } from 'react'
import Navbar from '../components/Navbar'
import ProductArtwork from '../components/ProductArtwork'
import { formatPrice } from '../format'
import { useCart } from '../useCart'
import './Sprint3.css'
const API_BASE=import.meta.env.VITE_API_URL||'http://127.0.0.1:8000/api'
const CartPage=()=>{
 const{items,itemCount,subtotal,updateQuantity,removeItem,clearCart}=useCart();const checkout=window.location.pathname.replace(/\/$/,'')==='/checkout';const delivery=items.length===0||subtotal>=2000?0:80;const total=subtotal+delivery;const stored=localStorage.getItem('nazriy-user');const user=stored?JSON.parse(stored):null
 const[form,setForm]=useState({name:'',email:user?.email||'',phone:'',address:'',city:'',postal_code:''});const[state,setState]=useState<'idle'|'loading'|'error'|'success'>('idle');const[message,setMessage]=useState('')
 const submit=async(event:FormEvent)=>{event.preventDefault();if(Object.values(form).some(v=>!v.trim())||!/^\S+@\S+\.\S+$/.test(form.email)||!/^[+\d][\d\s-]{7,}$/.test(form.phone)){setState('error');setMessage('Enter valid information in every required field.');return}const token=localStorage.getItem('nazriy-token');if(!token){setState('error');setMessage('Log in before placing your order.');return}setState('loading');try{const response=await fetch(`${API_BASE}/orders/checkout/`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Token ${token}`},body:JSON.stringify({...form,items:items.map(item=>({product_id:item.product.id,quantity:item.quantity,size:item.size,color:item.color}))})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.detail||'Unable to create the order.');clearCart();setState('success')}catch(error){setState('error');setMessage(error instanceof Error?error.message:'Unable to create the order.')}}
 if(state==='success')return <div className="site-shell"><Navbar/><main id="main-content" className="s3-state success"><span>✓</span><h1>Order confirmed</h1><p>Your order has been saved. We’ll send delivery updates to {form.email}.</p><div className="hero-actions"><a className="primary-button" href="/orders">Track your order</a><a className="secondary-button" href="/">Back to home</a></div></main></div>
 if(items.length===0)return <div className="site-shell"><Navbar activePage="cart"/><main id="main-content" className="s3-state"><span>0</span><h1>Your cart is empty</h1><p>Explore the collection and add a piece to continue.</p><a className="primary-button" href="/products">Browse products →</a></main></div>
 return <div className="site-shell"><Navbar activePage="cart"/><main id="main-content" className={checkout?'cart-page checkout-active':'cart-page'}><nav className="breadcrumbs"><a href="/">Home</a><span>/</span><span>{checkout?'Checkout':'Cart'}</span></nav><header className="cart-page-heading"><div><p className="eyebrow">{checkout?'Secure checkout':'Your selection'}</p><h1>{checkout?'Delivery information':'Shopping cart'}</h1></div>{!checkout&&<button onClick={clearCart}>Clear cart</button>}</header>
 <div className="cart-layout"><section className={checkout?'delivery-form-panel':'cart-items'}>{checkout?<form className="s3-delivery-form" onSubmit={submit} noValidate><div className="s3-field-grid">{([['name','Full name'],['email','Email'],['phone','Phone number'],['address','Address'],['city','City'],['postal_code','Postal code']]as const).map(([key,label])=><label key={key}>{label} *<input type={key==='email'?'email':'text'} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div>{state==='error'&&<p className="s3-error" role="alert">{message}</p>}{!user&&<p className="s3-login-note">Already have an account? <a href="/login">Log in</a> before placing your order.</p>}<button className="s3-place-order" disabled={state==='loading'}>{state==='loading'?'Creating order…':`Place order · ${formatPrice(total)}`}</button></form>:items.map(item=><article className="cart-item" key={item.key}><a className="cart-item-image" href={`/products/${item.product.slug}`}><ProductArtwork product={item.product}/></a><div className="cart-item-info"><p>{item.product.category.name}</p><h2><a href={`/products/${item.product.slug}`}>{item.product.name}</a></h2><div className="cart-item-options">{item.size&&<span>Size: {item.size}</span>}{item.color&&<span>Colour: {item.color}</span>}</div><button className="remove-item" onClick={()=>removeItem(item.key)}>Remove</button></div><div className="cart-item-controls"><div className="cart-quantity" aria-label={`Quantity for ${item.product.name}`}><button onClick={()=>updateQuantity(item.key,item.quantity-1)} aria-label="Decrease quantity">−</button><strong>{item.quantity}</strong><button disabled={item.quantity>=item.product.stock_quantity} onClick={()=>updateQuantity(item.key,item.quantity+1)} aria-label="Increase quantity">+</button></div><strong>{formatPrice(Number(item.product.price)*item.quantity)}</strong><small>{item.product.stock_quantity} in stock</small></div></article>)}</section>
 <aside className="order-summary"><p className="eyebrow">Checkout</p><h2>Order summary</h2><dl><div><dt>Items ({itemCount})</dt><dd>{formatPrice(subtotal)}</dd></div><div><dt>Delivery</dt><dd>{delivery===0?'Free':formatPrice(delivery)}</dd></div><div className="order-total"><dt>Total</dt><dd>{formatPrice(total)}</dd></div></dl>{subtotal<2000&&<p className="delivery-progress">Add {formatPrice(2000-subtotal)} more for free delivery.</p>}{checkout?<a className="s3-summary-action" href="/cart">← Edit cart</a>:<a className="s3-summary-action" href="/checkout">Continue to checkout</a>}<a href="/products">← Continue shopping</a></aside></div></main></div>
}
export default CartPage
